### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by dacconcio** [milaq/XMousePasteBlock#25]
Hi, thanks for developing this. When I run the app in arch it doesn't seem to do anything. When I click the middle mouse button, it still pastes.

**Comment by Jackenmen** [comment]
Try running from this commit (it's one commit before the latest): https://github.com/milaq/XMousePasteBlock/commit/94044984e4b3bd4086f3d5636f53c3a3117051fd

**Comment by dacconcio** [comment]
Thanks @Jackenmen. Is it possible to do that using the AUR?

**Comment by Jackenmen** [comment]
xmousepasteblock AUR package seems to pin at 1.2 which is equivalent to what I said already, xmousepasteblock-git doesn't seem to though so if you're using that, try switching.

**Comment by dacconcio** [comment]
I'm using the AUR. Is there anything else I can try? The program runs, but when I click on the middle mouse button while it's running it still pastes.

**Comment by Jackenmen** [comment]
Two things that come to my mind:
- make sure that you are actually using X11, this doesn't work with Wayland and while Wayland itself doesn't bind middle mouse button to paste, some desktop environments will simulate it on their own when running on Wayland which could make you think that you're using X11
- make sure that you're running it under the current session user - NOT as root

**Comment by Jackenmen** [comment]
> I'm using the AUR.

I noticed that you still haven't explicitly said *which* AUR package you are using :P

**Comment by dacconcio** [comment]
Yes, I'm using X11. I'm running it normally not with sudo or anything. 

I'm pretty new to linux/Arch, so I'm not sure I understand. It's the package located here: https://aur.archlinux.org/packages/xmousepasteblock-git

**Comment by Jackenmen** [comment]
Yeah, as I said earlier, if you're using xmousepasteblock-git package, you should try xmousepasteblock package instead, here's the link: https://aur.archlinux.org/packages/xmousepasteblock

**Comment by dacconcio** [comment]
Oh, I misunderstood. I'll try that now

**Comment by dacconcio** [comment]
It works! Awesome, thanks so much

**Comment by Jackenmen** [comment]
No problem, glad I could help :)

**Comment by lawnjelly** [comment]
I also found that reverting https://github.com/milaq/XMousePasteBlock/commit/8237434c85d524592507747783a1bd65f15b918e made it work. It didn't work on my Linux Mint 21.1 Cinnamon with the latest.

Maybe that commit should be revisited...

**Comment by pauloamed** [comment]
I also had to revert the last commit (https://github.com/milaq/XMousePasteBlock/commit/8237434c85d524592507747783a1bd65f15b918e) in order to make it work on Ubuntu 22

**Comment by RedSnt** [comment]
~~Tried both v1.3 and v1.2 and even did `make debug` and it says `Primary selection and cut buffer cleared` when using middle mouse button, yet still pastes. In KDE Plasma 2.27.5 there's no option in Klipper to "prevent empty clipboard" which I'm suspecting is the culprit. Sucks, because middle mouse button paste is just silly.~~

EDIT: Oh, I feel silly for not reading [this readme part about ~/.config/klipperrc](https://github.com/ZacharyTalis/XMousePasteBlock/blob/master/README.md) (although from a fork of this project).
EDIT2: Ohhh, so apparently `NoEmptyClipboard` needs to be set to `true` now for this to work, because it was [a bug that has been fixed according to this](https://bugs.kde.org/show_bug.cgi?id=432819). Setting it to true makes it work for me now using v1.2 🥳
EDIT3: After a restart it stopped working, so not sure what Klipper's deal is, but disabling it altogether fixes it. Going to use another clipboard manager since that's the culprit. CopyQ seems decent, and it works with XMousePasteBlock 👍

**Comment by milaq** [comment]
Should be fixed by https://github.com/milaq/XMousePasteBlock/commit/0f4c279790f212a8835c3d3c6176775ef79d1ea7

**Comment by Thespikedballofdoom** [comment]
I've done this fix but unfortunately still get issues where some programs paste, either once, only when unfocused, or completely ignore Xmousepasteblock, even with the klipperrc fix and watch slave devices. https://unix.stackexchange.com/a/501445 is working well for me though
